### ISSUE TITLE
Datadog-ize logs

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#10]
Match their spec, behind flag if not human-friendly enough for default

https://docs.datadoghq.com/logs/log_collection/python/

**Comment by myhndl** [comment]
This is a larger issue than just `polyswarm-client`; we'll want to do this across many projects. Once complete, let's re-file in `development` repo and track other projects as well.

**Comment by myhndl** [comment]
Moved: https://github.com/polyswarm/development/issues/30
