### ISSUE TITLE
Microengine run without arguments doesn't use an appropriate backend

### ISSUE THREAD

**Issue by zv** [polyswarm/polyswarm-client#111]
**Describe the bug**
Running the `microengine.exe` binary from a `virtualenv` setup on Windows does not start the correct backend.

**To Reproduce**
1. `PS C:\> git clone git@github.com:polyswarm/engine-lionic.git`
2. Setup & run `virtualenv` activation function
3. Modify `__init__.py:Microengine` to give some indication it's been loaded.
4. `PS C:\engine-lionic> pip install -r requirements.txt`
5. `PS C:\engine-lionic> python setup.py install`
6. `PS C:\engine-lionic> microengine --keyfile ...`

**Expected behavior**
Run `microengine.exe` with an implicit backend of `polyswarm_lionic`

**Comment by scsich** [comment]
I'm not sure this is actually critical. You should be either passing your engine backend as the `BACKEND` env variable or `--backend`

https://github.com/polyswarm/polyswarm-client/blob/master/src/microengine/__main__.py#L57

Moving out of stable critical, but keeping bug label until issue closed/updated @zv

**Comment by myhndl** [comment]
It's critical if docs are wrong. Running through docs again now to verify.

Fix will be simply to fix docs.

**Comment by myhndl** [comment]
unable to repro in linux integration tests, will try windows next

**Comment by myhndl** [comment]
Yeah you're right @mrtizmoatwork - I did not test thoroughly enough. I figured not specifying a backend would throw an exception. Instead, it uses the `scratch` backend, which does nothing.

I think this is undesirable. I think `--backend` should be a required parameter.

Will file tickets, correct docs and engine-template.

**Comment by myhndl** [comment]
fixed (on linux) via https://github.com/polyswarm/engine-template/pull/10

**Comment by myhndl** [comment]
i think we can close this - windows docs are correct, linux doc update in progress, engine-template fixed for linux integration testing
