### ISSUE TITLE
Update docs IAW asyncio changes

### ISSUE THREAD

**Issue by mrtizmoatwork** [polyswarm/polyswarm-client#131]
**Is your feature request related to a problem? Please describe.**
We changed clamav microengine code and we forked clamd python package (python-clamd), so we need to update our docs accordingly.

**Describe the solution you'd like**
1. Update docs.polyswarm.io with new async code examples and any necessary call outs regarding use of asyncio.
2. Update the README in the python-clamd repo to have an example of using the asyncio-supported class we added (ClamdAsyncNetworkSocket).

**Describe alternatives you've considered**
No

**Additional context**
python-clamd repo: https://github.com/polyswarm/python-clamd

**Comment by myhndl** [comment]
@mrtizmoatwork closing this; I think it's done, am I missing something here?
