### ISSUE TITLE
Multi-artifact uploads broken

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#132]
**Describe the bug**
Pretty sure multipart encoding isn't right, works via curl but not client, get `File argument 'path' is required`

**Comment by mrtizmoatwork** [comment]
@myhndl do we want this in January or February milestone?

**Comment by Rizato** [comment]
Consumer upload was able to put multiple files into ipfs through polyswarmd. It uses a modified version of the polyswarm-client upload. 

I will continue to try to reproduce this later.

**Comment by Rizato** [comment]
Attempt to reproduce with with filesystem ambassador uploaded fine and showed microengine responding to two files. 

Cannot test with staging as it is configured to only allow one file (And is currently down)

**Comment by mrtizmoatwork** [comment]
@Rizato what are the next steps for this Issue?

**Comment by mrtizmoatwork** [comment]
@supernothing can you help test and track this down too?

**Comment by supernothing** [comment]
This appears to be an [IPFS error](https://github.com/ipfspics/ipfspics-server/issues/12) getting returned by `polyswarmd`, related to a missing path argument which is the filename `polyswarm-client` provides.

I'm not sure how it's related to multi-artifact uploads here, but the likely culprit to me is that filename gets through [these checks](https://github.com/polyswarm/polyswarm-client/blob/7cb5b5b03f279d815dc0d5c3ab36bfdfc0d6a0e3/src/polyswarmclient/__init__.py#L663) and is still `None`, which can happen if `f` does not have attribute `name`. Maybe setting a default filename here is the solution.

@mjkoo, how did you test exactly? Maybe that can help explain.

**Comment by mjkoo** [comment]
Extracted out post_artifacts logic into a test script and posted multiple artifacts a few different ways, examined request and response, also could not reproduce error. Setting a default filename seems reasonable.

**Comment by supernothing** [comment]
Closing, think that fixed it. Will re-open if it pops up again.
