### ISSUE TITLE
Cannot POST artifacts to IPFS with no filename

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarm-client#145]
**Describe the bug**
We've seen this manifest in `ambassador` and `consumer` - it cannot POST to IFPS, causing all sorts of issues further down the line.

Recent issues with Consumer:
https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%2C%22log_http.status_code%22%2C%22log_request_Authorization%22%5D&context_event=AAAAAWgQPYQAqYsJbgAAAABBV2dRUFlRQ1NzbW9JUG45aG5uQQ&event=&from_ts=1546459805596&index=main&live=false&logset=main&messageDisplay=inline&query=host%3Ai-0204db9b81e4a3d76+service%3Aconsumer+container_id%3A6c144c2d04cf7bae5cbbc377284ad7dcf830697d335123e3b25a797ccbe9aa36&saved_view&stream_sort=desc&to_event=AAAAAWgQPYRHqYsJfgAAAABBV2dRUFlSTFNzbW9JUG45aG5xNg&to_ts=1546460693575

**To Reproduce**
Run `ambassador` / `consumer` for a long time, experience existential sadness.

**Expected behavior**
We can successfully post to `post_artifacts` route, including hosting on IPFS.

**Additional context**

**Comment by Rizato** [comment]
Working on a solution on consumer to handle uploads to ipfs in consumer_frontend. Hoping to resolve the issue where consumer can't upload to ipfs. 

I have made the modifications to consumer for this, but have run into issues actually running and pushing the files into ipfs. I think my problem is that I have been trying to hack together polyswarm-client to do the trick, but it was never meant to let you upload to ipfs without running the client. (Which I don't want to do).

I am going to rip out the upload logic from polyswarm-client and use that to upload without the whole client.

**Comment by Rizato** [comment]
Changes going up on stage now.

**Comment by Rizato** [comment]
I think we discovered the ipfs failures were due to missing names, not so much after a while.

**Comment by Rizato** [comment]
After looking at this some more, it turns out flask is the one that won't take files without a filename. 

The reason consumer was sending without filesnames, since it can't take files without filesnames is that it was receiving files with the name `/`. We pass it through os.basename which blew away the name. 

So I think I will do an earlier check on os.basename and reject files in consumer that come back with strings with no content.

@myhndl @mjkoo @mrtizmoatwork

**Comment by Rizato** [comment]
Closing in favor of consumer#109
