### ISSUE TITLE
Crashes if it cannot retrieve bounty parameters

### ISSUE THREAD

**Issue by Rizato** [polyswarm/polyswarm-client#149]
**Describe the bug**
If polyswarm-client cannot get the bounty params due to a network error, it leads to a crash

**To Reproduce**

**Expected behavior**
Log an error and continue

**Additional context**
```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/asyncio/tasks.py", line 242, in _step
result = coro.throw(exc)
File "/usr/local/lib/python3.5/site-packages/polyswarmclient/__init__.py", line 196, in run_task
await self.bounties.get_parameters(chain)
File "/usr/local/lib/python3.5/site-packages/polyswarmclient/bountiesclient.py", line 26, in get_parameters
raise Exception('Error retrieving bounty parameters')
Exception: Error retrieving bounty parameters
ERROR:polyswarmclient:2019-01-03 15:54:15,579 Detected unhandled exception, exiting with failure
```

**Comment by mjkoo** [comment]
Related to #144 I think we need to change our top-level exception handler to basically tear down and restart the task, possibly with backoff, but then also handle exceptions more locally when possible such as the websocket exception in #146 .

In the case of a network error like this during init, we should probably just catch at the top level, log it, and then restart run_task after a bit I think
