### ISSUE TITLE
Balance-manager maintain CLI function does not support log formats

### ISSUE THREAD

**Issue by aarongooch** [polyswarm/polyswarm-client#161]
**Is your feature request related to a problem? Please describe.**
Balance Manager maintain CLI function should Log in JSON format

**Describe the solution you'd like**
Add cli flag `--log_format` and configure logger

**Describe alternatives you've considered**
This is it

**Additional context**
No sir

**Comment by aarongooch** [comment]
After looking at the code base a bit more thoroughly I notice `--log-format` should be supported by the `cli` group. This log output says otherwise.

https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22tag_swarm_service%22%2C%22tag_poly_work%22%2C%22tag_container_name%22%2C%22tag_engine_name%22%5D&context_event=AAAAAWgrR1DLx9PFfwAAAABBV2dyUjFETFo1M1lnVmxnekZuVw&event=AAAAAWgrR1DLx9PFfwAAAABBV2dyUjFETFo1M1lnVmxnekZuVw&from_ts=1546912624047&index=main&live=false&logset=&messageDisplay=inline&query=host%3Ai-0e48433ba9fefe1ae+service%3Apolyswarm-client+container_id%3A5c49825d380c08c9df6edb8541cbd39b77b547ac0dfd96d120d7b1a8dc2516dc&queryString=error+-image_name%3A%28%22google%2Fcadvisor%22+OR+%22datadog%2Fagent%22+OR+%22stefanprodan%2Fcaddy%22%29+poly_work%3Aprod&saved_view&stream_sort=desc&to_ts=1546914320587

**Comment by aarongooch** [comment]
Issue is in the compose file. `--log-format` should be specified before the `maintain` cmd

**Comment by Rizato** [comment]
Closing as stated above `--log-format` is an option to `balancemanager` not the sub commands.
