### ISSUE TITLE
Explicitly Handle (In)Secure polyswarmd Transport

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarm-client#2]
Acceptance criteria:
* [ ] user cannot directly specify schema
* [ ] `https` / `wss` assumed
* [ ] new flag `--insecure-transport` overrides to `http` / `ws`
* [ ] `--insecure-transport` and `--api-key` are mutually exclusive arguments, fatal error
* [ ] fix up all the usages of these args in various compose files to remove schema

**Comment by scsich** [comment]
I say the following:

1. full URL expected, you use URLparse and can get everything broken out
2. `--api-key` && `--insecure-transport` allowed
3. `--api-key` && urlparse.transport == 'http'  fail
4.  wss/ws chosen based on http/https from urlparse

Using URL parse gets you basicauth, protocol, port, and IP vs DNS everywhere. Minimal changes required for non-API key using tutorials.

**Comment by myhndl** [comment]
Attempting to reconcile the two designs and be more explicit:
1. if full URI provided, `scheme` taken from URI using URLparse, else `scheme` = `http`
1. if `scheme` != `https` && `scheme` != `http`, hard fail
1. if `scheme` == `http` && not `--insecure-transport`, hard fail
1. if `scheme` == `http` && `--api-key`, hard fail
1. if `scheme` == `http`, `websocket_scheme` = `ws`
1. if `scheme` == `https`, `websocket_scheme` = `wss`

**Comment by myhndl** [comment]
Currently we are not gracefully handling schema presented via the `polyswarmd-addr` argument and we should.

Works: `gamma-polyswarmd.stage.polyswarm.network`

Doesn't work: `https://gamma-polyswarmd.stage.polyswarm.network`
