### ISSUE TITLE
Dis-trust polyswarmd

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#26]
Check parameters and addresses to the best of our ability, what we are able to do is somewhat limited due to visibility into the state of the blockchains.

Distilled from issues across ambassador/arbiter/microengine

**Comment by myhndl** [comment]
@Rizato you did some work on this, right? Where do we stand on this?

**Comment by Rizato** [comment]
I had worked on it a bit in arbiter a while back. I don't think that made it over into  polyswarm-client. 

I think it should be straightforward enough though.
