### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#29]
Docs aren't somewhat there but not complete, should endeavor to

- [ ] Docstrings for everything: https://github.com/polyswarm/development/issues/17
- [ ] Autogen docs on e.g. readthedocs
- [ ] Reference tutorials on docs.polyswarm.io

https://github.com/polyswarm/ambassador/issues/17 indicates that offers need better docs too, reported by @ceseale

**Comment by myhndl** [comment]
Trevor got started on this last week, will continue this week.

**Comment by myhndl** [comment]
Moved to: https://github.com/polyswarm/development/issues/29
