### ISSUE TITLE
Horizontal Microengine Scaling: Cross-{process|container|machine} nonce sync

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#32]
Transactions need to be ordered with a sequential nonce value, this complicates scaling up clients. Provide a default implementation of syncing current nonce cross container, allow for different methods should implementations choose so.

**Comment by myhndl** [comment]
semi-related: https://github.com/polyswarm/development-private/issues/14

**Comment by mrtizmoatwork** [comment]
Closing in favor of: https://github.com/polyswarm/development-private/issues/154
