### ISSUE TITLE
Filename from scan func

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#36]
**Is your feature request related to a problem? Please describe.**
Polyswarmd can get back filename from artifacts if uploaded using the conventional multi-file artifact process (`POST /artifacts`), we should give this information to Scanners

**Describe the solution you'd like**
Add optional filename parameter to scan methods, this shouldn't be a breaking change, can't assume we always have a filename for an artifact

**Comment by myhndl** [comment]
@mjkoo @zv what's the status on this? This has been open for a while with no comments here, but a move to Needs Review

**Comment by mjkoo** [comment]
I have no idea why this was moved. This hasn't blocked progress on anything so hasn't been a priority / started afaik.

**Comment by zv** [comment]
I think I misunderstood the role of "Needs review" when I was just starting out. Sorry guys!

**Comment by myhndl** [comment]
Heh no problem at all! Was just trying to get to the bottom of it :)
