### ISSUE TITLE
Gracefully Handle non-JSON Results

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarm-client#41]
polyswarmd always returns a JSON response, but we have other parts of the stack running in front of it now (load-balancer, etc) which may not. We discussed failing on unexpected responses/connection errors and waiting for container restart in lieu of other recovery methods (ref https://github.com/polyswarm/polyswarm-client/pull/31).

- [ ] Add logging in case of non-json response, this may happen occasionally
- [ ] Evaluate failure strategy to prevent downtime

**Comment by myhndl** [comment]
Applying blocker label because this has resulted in critical reliability issues. We need to address ASAP.

**Comment by myhndl** [comment]
User must be able to rely on `polyswarm-client` to not quit because it gets an invalid response. We need to take the Wireshark track here: handle everything in the pursuit if staying up.

**Comment by myhndl** [comment]
Right now we're (ab)using this behavior as a means to forcefully reset `polyswarm-client` based projects when a new infrastructure deploy happens or Traefik fails, etc.

We must change this behavior to be resilient in the face of error prior to 1.0 release. That said, he have other more pressing issues at the moment, so I'm moving to release column.

**Comment by mjkoo** [comment]
Closed by #126
