### ISSUE TITLE
Potential Logic Bug in `src/polyswarmclient/reporter.py`

### ISSUE THREAD

**Issue by telwell** [polyswarm/polyswarm-client#44]
**Describe the bug**
```
    def mark_stage_complete(self, s):
        """
        Pass in the stage you want to mark as complete, it gets verified
        as a valid state transition and stored in the class.

        Args:
            s (str): State to mark complete
        """
        expected_current_stage = self.valid_transitions.get(s)
        if expected_current_stage == self.stage:
             # NOTE: Not sure why we go back to stage s here if we're making it complete?
            self.stage = s
            return
        raise Exception('Invalid state transition {0} -> {1}'.format(self.stage, s))
```
We pass in an argument `s` which is the name of the stage we want to mark as complete. This appears to assume that `self.stage` has already transitioned to the next stage. If so, we validate that `self.stage` is a valid transition from the `s` we pass in. But then, if the transition is valid, we set `self.stage = s` which appears to revert us back to the stage we're marking complete? Perhaps I'm not following the logic here, but this seems like a potential logic bug.

**Comment by myhndl** [comment]
@mjkoo could you take a quick look at this?

**Comment by myhndl** [comment]
bump @mjkoo

**Comment by myhndl** [comment]
bump @mjkoo
