### ISSUE TITLE
Dockerfile specifies 005789955001.dkr.ecr.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by p00temkin** [polyswarm/polyswarm-client#484]
**Unable to build new path to python:3.7-slim-buster**
The docker/Dockerfile was changed to specify an explicit path to AWS, which prevents proper builds. 

**To Reproduce**
1. git clone repo
2. docker build -f docker/Dockerfile .
3. See error

Sending build context to Docker daemon  612.9kB
Step 1/10 : FROM 005789955001.dkr.ecr.us-east-1.amazonaws.com/python:3.7-slim-buster
Get https://005789955001.dkr.ecr.us-east-1.amazonaws.com/v2/python/manifests/3.7-slim-buster: no basic auth credentials

**Expected behavior**
Reference to accessible python:3.7-slim-buster

**Additional context**
git diff 96bd7dbaadf38fc3135219be4a03c0742688d014 25b885c130088169f73906f2df7c9a8181a2bac2 docker/Dockerfile
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 6c812d0..f2e07b9 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,4 @@
-FROM python:3.7-slim-buster
+FROM 005789955001.dkr.ecr.us-east-1.amazonaws.com/python:3.7-slim-buster

**Comment by mrtizmoatwork** [comment]
thanks for the note. I'll have a fix for this shortly.

**Comment by Rizato** [comment]
Fixed in #485. Let us know if you have any other issues.
