### ISSUE TITLE
Replacement transaction error

### ISSUE THREAD

**Issue by ceseale** [polyswarm/polyswarm-client#58]
_From @ceseale on October 19, 2018 14:30_

**Describe the bug**

> .. I was getting nonce errors before staking, staked (which failed with 'replacement transaction underpriced'), but then it started working again

**Expected behavior**
Needs investigation, might be a nonce issue.

What does the error mean?

> "Returned error: replacement transaction underpriced"

The error means that:
1. You have a pending transaction from your account in your Ethereum client
1. The new transaction you are sending has the same nonce as that pending transaction
1. The new transaction you sent has a gas price that is too small to replace the pending transaction

**Additional Information**
https://stackoverflow.com/questions/46349202/rinkeby-replacement-transaction-underpriced

[datadog logs](https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&event=AAAAAWaM3Vb5gvI0fgAAAABBV2FNM1ZiMDZqMXdvdmdQaDEwNw&from_ts=1539960757981&index=main&live=true&query=container_name%3Agamma_polyswarmd.%2A+-status%3A%28warn+OR+info%29&stream_sort=desc&to_ts=1539961657981)

_Copied from original issue: polyswarm/polyswarmd#97_

**Comment by myhndl** [comment]
@ceseale what's the status on this?
