### ISSUE TITLE
Error noise: nonce too low

### ISSUE THREAD

**Issue by zv** [polyswarm/polyswarm-client#59]
Datadog reported an issue with polyswarmd @  `gamma_polyswarmd.1.iuznk74508nzola7unz67fhzx` on Friday 19th @ 16:38 PST.

> ERROR:root:Got transaction errors: ["Invalid transaction error for tx 268fee810f2d8a960e5eab1062ce4cf727e832a39817737893e726867512bfc1: {'code': -32000, 'message': 'nonce too low'}", "Invalid transaction error for tx 47d4352c5fb96517ea7d502b9c211997b83b4841857d3a7aaf9a47853ba50c4d: {'code': -32000, 'message': 'nonce too low'}"]

**Comment by myhndl** [comment]
This will happen if a microengine has two threads that attempt to submit a transaction at approximately the same time. It's expected; microengines move to re-sync nonces in such a case.

Related: https://medium.com/kinblog/making-sense-of-ethereum-nonce-sense-3858d5588c64

That being said, this should not be an ERROR level message. This amounts to noise. Please reduce error level to INFO and close this ticket when done @zv

**Comment by zv** [comment]
![screenshot](https://user-images.githubusercontent.com/987494/48226478-bfd58680-e354-11e8-8cae-68ab6269c496.png)

**Comment by myhndl** [comment]
Leaving as ERROR level for now. Maybe we can filter at Datadog layer. Closing as invalid.
