### ISSUE TITLE
Add status endpoint

### ISSUE THREAD

**Issue by eodgooch** [polyswarm/polyswarm-client#63]
**Is your feature request related to a problem? Please describe.**
Process stops responding to requests. We should be proactive in culling bad processes in the docker swarm. This will ensure stability of the system without human intervention. Bad services die and are replaced with healthy services.

**Describe the solution you'd like**
Add an endpoint `status` with a query parameter `client_type=[ambassador|arbitor|engine|...]` that can be called by the docker swarm healthcheck component that yields a 200 response code if OK or 500 response code if not OK. The endpoint should perform some basic sanity check to ensure the process is behaving correctly. This could be verifying the websocket connection and/or some similar integration point.

**Describe alternatives you've considered**
Another option would be cull the process after subsequent failed requests but this will involve creating some in memory stateful data structure.

**Additional context**
This endpoint should be called from the docker compose service using the `healthcheck` [docker compose functionality](https://docs.docker.com/engine/reference/builder/#healthcheck)

**Comment by myhndl** [comment]
To be clear: this is about healthchecking services built on `polyswarm-client` (e.g. microengines) or services used by `polyswarm-client` (e.g. `polyswarmd`).

I'm virtually certain you mean the former, but don't know why we'd need a client type. The process will already be acting as one type of engine. It should conduct a status check as appropriate for that engine IMO.
