### ISSUE TITLE
Mocking Polyswarmd's HTTP endpoints

### ISSUE THREAD

**Issue by zv** [polyswarm/polyswarm-client#73]
Much of **`polymon-client`**'s code services HTTP requests to **`polyswarmd`**. To ensure test-coverage of these components, we require a flexible method to mock responses to & from `polyswarmd` (flexibly)

## Approaches

The following are the outlines of my thoughts this morning on the details of this feature.

I hope to solicit feedback and criticism from the rest of @polyswarm/tech on the best approach, alongside other's thoughts on potential blockers and features.

###  In-process; sans-socket

The approaches I'm calling *sans-socket* implement the mock without actually setting up a socket and thus are handling this "in process".

#### *monkey-patching* / injection

[*monkey-patching*](https://en.wikipedia.org/wiki/Monkey_patch) libraries responsible for carrying out HTTP requests or even network IO could create tests cases which specify (typically **within** the test-case itself) what the intended response to a particular request should be & replacing their yield/return values with our "test response"

Our test cases, at a high level, a test might look like the following:

1. Hook [`request`](http://docs.python-requests.org/en/master/), looking up our expected server response in a `URL (+ verb/etc.) => test response` "table" (or in the test case itself).
2. Invoke a function which hits `polyswarmd`, no need to consider the actual endpoint host/port.
3. Call that function
4. Look up our expected result in aforementioned table, and `assertEqual` (or provide the expected response in the test case itself)

#### Refactor / function extraction

Breaking up the methods in `polyswarm-client` which currently initiate HTTP requests such as [**`make_request`**](https://github.com/polyswarm/polyswarm-client/blob/167f9b0ae0433cad281b763843dac9efeec442bf/src/polyswarmclient/__init__.py#L187) (or even higher-level functions), we could refactor the code with a view towards a codebase where the machinery of making a request is separate from the logic of handling that request.

We would then test each of the actions abstractly, looking at the internal representation of the Python object returned rather than a response code, JSON string, etc.

#### A real, fake server; *`polymock`*

Cuckoo team's arbiter already includes [a mocked implementation of `polyswarmd` - `polymock`](https://github.com/polyswarm/arbiter-cuckoo/blob/master/polymock/polymock.py) in the form of a flask application.

Our mocked implementation could borrow extensively from `polymock`, but ideally provide expected responses to a particular endpoint as ordinary functions, allowing us to test `polyswarm-client` without a mock HTTP server.

#### `polyswarmd`

This approach is likely to be too slow to be suitable for integration into a CI system's pipeline, but might be useful for an integration-focused test harness.

## Nice-to-haves

- Returning chaotic / random responses, instrumenting "web application fuzzing"
- Providing a way to run tests quickly, upto-and-including running in-process without actually speaking HTTP
- Integrating with tracing system / providing a quick way to determine if there have been performance regressions
- Readily runs from a docker image or binary

**Comment by mjkoo** [comment]
monkey patching approach is in progress in feature/unit-tests branch, I think consumer is taking a similar approach
