### ISSUE TITLE
Logs that contain JSON objects, should log fully as JSON

### ISSUE THREAD

**Issue by Rizato** [polyswarm/polyswarm-client#79]
**Is your feature request related to a problem? Please describe.**
We print of a lot of logs similar to the following `logger.info('Received settled bounty on chain %s: %s', chain, data)`
We end up having logs where the inner JSON is not parsable by datadog per https://github.com/polyswarm/development-private/issues/73

**Describe the solution you'd like**
Add wrap the `data` json object inside a new one containing the message and chain

**Comment by aarongooch** [comment]
To pass a python dict to the log statement you can use `logger.info('my message', extra={'key': 'value'})` https://docs.datadoghq.com/logs/log_collection/python/

**Comment by Rizato** [comment]
Ah, that is even better.

**Comment by Rizato** [comment]
Hmm. That doesn't work for the text log version.

**Comment by Rizato** [comment]
Figured it out. Had to build a custom formatter.
