### ISSUE TITLE
CI on master branch reports windows build fails

### ISSUE THREAD

**Issue by Rizato** [polyswarm/polyswarm-client#85]
**Describe the bug**
CI fails on the wheels step, which is part of the windows build process. 

**To Reproduce**
1. Create a new PR
2. Merge or squash the PR
3. Click the CI result indicator on the commits pag
4. See failed step in pipeline

**Expected behavior**
All steps in pipeline pass

**Additional context**
https://gitlab.polyswarm.io/externalci/polyswarm-client/pipelines/4750

**Comment by scsich** [comment]
Investigating, appears windows CI runner and timeout related right now.

**Comment by scsich** [comment]
@mb2con says transient failure in Windows CI runner, he removed one from list. I've reran pipeline here and its fine:
https://gitlab.polyswarm.io/externalci/polyswarm-client/-/jobs/6960
