### ISSUE TITLE
Switch CLI chains default to side

### ISSUE THREAD

**Issue by Rizato** [polyswarm/polyswarm-client#94]
**Is your feature request related to a problem? Please describe.**
With relay up, we are moving everything to the sidechain. Having the default set to homechain has tripped things up a few times. 

**Describe the solution you'd like**
Set default to sidechain

**Additional context**
Similar to #87

**Comment by myhndl** [comment]
Also switch routes in `polyswarmd` to default to `side` if `?chain=XXX` is not specified. FYI @mjkoo

**Comment by Rizato** [comment]
Good Call
